[package]
name = "fuzz_os"
version = "0.1.0"
authors = ["Emile Yvan Boutet Livoff <blemille@hotmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.1.0"
spin = "0.4.5"
